### ISSUE TITLE
shinyapps: cannot load ecoli data sets

### ISSUE THREAD

**Issue by ebey** [statnet/statnetWeb#33]

**Comment by ebey** [comment]
The shinyapps webpage grays out when trying to load networks ecoli1 or ecoli2

Initial investigation shows that this is not caused by errors in trying to calculate centralization measures at startup. Currently looking into worker settings through shinyapps.io

**Comment by ebey** [comment]
Using https://ebey.shinyapps.io/statnetWeb to diagnose:

shinyapps log doesn't have any errors, or any messages at all after startup:

```
2015-05-13T18:10:14.756663+00:00 shinyapps[23088]: Listening on http://0.0.0.0:41816
```

**Comment by kecoli** [comment]
I run the app in local, for two ecoli networks, getting error 
Error in solve.default(A, tol = tol) : 
  system is computationally singular: reciprocal condition number = 1.7338e-21

other networks are fine.

**Comment by ebey** [comment]
Thanks @kecoli 

Those errors are from computing the information centrality and eigenvector centrality measures, but it seems to be a separate issue because when I comment them out and re-deploy (which I have done in https://ebey.shinyapps.io/statnetWeb) the app still dies when I select either of those networks.

**Comment by ebey** [comment]
Issue is fixed after increasing application size on shinyapps.io to XXL

**Comment by martinamorris** [comment]
hahahahahah

On Fri, 15 May 2015, ebey wrote:

> 
> Issue is fixed after increasing application size on shinyapps.io to XXL
> 
> —
> Reply to this email directly or view it on GitHub.[AH0J4n0kiMrqibln3W6ZnFz5_U6QX_OPks5oJn4JgaJpZM4EXRoA.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/
