### ISSUE TITLE
library refs in server.R

### ISSUE THREAD

**Issue by smjenness** [statnet/statnetWeb#40]
Just a minor note on loading libraries in your inst folder files.

Now that you have all these packages as depends, this:
https://github.com/statnet/statnetWeb/blob/master/inst/shiny/server.R#L2-L8

can just be replaced with:
```r
library(statnetWeb)
```

One thing that you may have found out from trying to deploy to shinyapps.io is that it will not accept a package that is built locally, but it will accept one built from github. Therefore, after you commit to github, you need to:

1. Install statnetWeb with `devtools::install_github("statnet/statnetWeb")
2. Then deploy

**Comment by ebey** [comment]
Thanks!
