### ISSUE TITLE
Online version of statnetWeb can't replicate NME Day 2 add health four model comparison

### ISSUE THREAD

**Issue by smjenness** [statnet/statnetWeb#56]
Specifically, in the third model with just attribute mixing (without gwesp), this error message when doing the goodness of fit statistics
```r
Error: coef has 20 elements, while the model requires 19 parameters.
```

**Comment by ebey** [comment]
I haven't been able to recreate this error, locally or with the online version. I will continue investigating.

**Comment by ebey** [comment]
Still can't recreate. Closing issue.
