### ISSUE TITLE
Package structure revision needed to deploy

### ISSUE THREAD

**Issue by martinamorris** [statnet/statnetWeb#69]
Shiny app package structure requirements have changed since this was first written.  When I try to deploy to the shinyApps.io server I get the following error:

> deployApp()

> Error in lint(appDir, appFiles, appPrimaryDoc) : 
>   Cancelling deployment: invalid project layout.
> The project should have one of the following layouts:
> 1. 'shiny.R' and 'ui.R' in the application base directory,
> 2. 'shiny.R' and 'www/index.html' in the application base directory,
> 3. 'app.R' or a single-file Shiny .R file,
> 4. An R Markdown (.Rmd) document,
> 5. A static HTML (.html) or PDF (.pdf) document.
> 6. 'plumber.R' API description .R file
> 7. 'entrypoint.R' plumber startup script
> 8. A tensorflow saved model

**Comment by skhan890** [comment]
I think I know what's going on here. can you `setwd("inst/shiny")` before running the deployment?

**Comment by martinamorris** [comment]
Thx, solved one problem, led to the next:

```
> deployApp("statnetWeb", 
+           appName = "statnetWeb", 
+           account = "statnet")
Error in deployApp("statnetWeb", appName = "statnetWeb", account = "statnet") : 
  F:\GitHub\StatnetOrganization\statnetWeb\inst\shiny\statnetWeb does not exist
```

The only things in the inst\shiny folder are global.R server.R and ui.R, and a folder www

What is this expecting?

**Comment by skhan890** [comment]
Ah... I think whoever made this repo did not push up the "shinyapps" folder, as shown in the repo below:
https://github.com/statnet/statnetWeb/blob/6d0c3898133a1234684e8471ed214809699337dc/.gitignore#L18

Do you have the login information for the shinyapps for statnet? I can investigate this further there. I have a feeling that the shinyapps folder might be on there as part of a zipped folder.

**Comment by skhan890** [comment]
Oh on second thought, this might just be a directory issue. Can you create a new folder called "statnetWeb" from inside of inst/shiny, and THEN deploy it (still from the getwd of "inst/shiny").

The file structure would then look like this:
statnetWeb
 - inst
    - shiny
      - statnetWeb
          - global.R
          - server.R
          - ui.R

**Comment by martinamorris** [comment]
trying this now.  have pushed all the changes

... seems to be working ;)
