### ISSUE TITLE
CRAN error

### ISSUE THREAD

**Issue by martinamorris** [statnet/statnetWeb#70]
CRAN folks found the following error and have asked us to fix it:

```
Found the following \keyword or \concept entries
which likely give several index terms:
  File 'run_sW.Rd':
    \keyword{GUI,}
```
The offending line is [here](https://github.com/statnet/statnetWeb/blob/6d0c3898133a1234684e8471ed214809699337dc/R/run_sw.R#L7)

Any idea what they're asking for?

**Comment by skhan890** [comment]
We need to delete the comma `,` separating the two keywords, according to Roxygen2 documentation (https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html). I'll make the change and push it up.

**Comment by skhan890** [comment]
@martinamorris Okay - this is now fixed! https://github.com/statnet/statnetWeb/blob/master/R/run_sw.R#L7

You can push up to CRAN again.

**Comment by skhan890** [comment]
I also ran the `devtools::check()` function on the fixed statnetWeb repo. This gave no errors, so hopefully it should go through CRAN smoothly!

![image](https://user-images.githubusercontent.com/15852734/59531352-9789a980-8e9a-11e9-9e18-f9847a1ee0a0.png)

**Comment by martinamorris** [comment]
Yup, it passed that check before I submitted yesterday.  It's not uncommon for this check to be fine, but CRAN still reject for other reasons.  

But I've fixed the two things they noted (with your help, thx) and have resubmitted.

**Comment by martinamorris** [comment]
Should leave this open until CRAN approves the submission

**Comment by martinamorris** [comment]
This was finally fixed by running roxygen to update the .Rd files
