### ISSUE TITLE
Term documentation not working properly

### ISSUE THREAD

**Issue by martinamorris** [statnet/statnetWeb#87]
# Shiny server version not working

* no search box appears
* links to docs are broken, for example "Commonly used terms" points to the link below and brings up a window with the code https://github.com/statnet/statnetWeb/blob/master/inst/html/d2-sX-ergmterms.html

![image](https://github.com/user-attachments/assets/dea29c47-b02c-4f29-9f4e-2dea789ec153)

# Locally built with ergm 4.6.0 also not working

* search box appears
* text for term definition not rendering properly:

![image](https://github.com/user-attachments/assets/57ba3e1b-8f00-4912-b0b7-68865e48a413)

**Comment by krivit** [comment]
Has `statnetWeb` ever been updated to use the new documentation format and tools?
